name: Crawl

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Crawl
        run: curl -X GET "https://www.buskerlabel.com/crawl"
