name: Crawl

on:
  schedule:
    # once a day at 2:10 AM
    - cron: "10 2 * * *"
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Crawl
        run: curl -X GET "https://www.buskerlabel.com/crawl"
