name: Shortlist

on:
  schedule:
    # once a day at 2:30 AM
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Crawl
        run: curl -X GET "https:/www.buskerlabel.com/shortlist"
