name: Shortlist

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Crawl
        run: curl -X GET "https://buskerlabel.com/shortlist"
